// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'functional_unit_pool.freezed.dart';

@freezed
class FunctionalUnitGroupCfg with _$FunctionalUnitGroupCfg {
  const factory FunctionalUnitGroupCfg({
    required int operationLatency,
    required int issueLatency,
    required int numUnits,
  }) = _FunctionalUnitGroupCfg;
}
