// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/simple.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'register.freezed.dart';

@freezed
class XRegisterFile with _$XRegisterFile {
  const factory XRegisterFile({
    required U64Array32 regs,
  }) = _XRegisterFile;
}
